server.port: 1001

## database config
spring :
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource :
    url: jdbc:postgresql://localhost:5432/airbnb.com
    username: postgres
    password: rana


## logging
logging:
  level:
    root : info
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

